// skillsData.js

const skillsData = [
    { id: 1, name: "JavaScript" },
    { id: 2, name: "Python" },
    { id: 3, name: "Java" },
    { id: 4, name: "C++" },
    { id: 5, name: "HTML" },
    { id: 6, name: "CSS" },
    { id: 7, name: "React" },
    { id: 8, name: "Node.js" },
    { id: 9, name: "Express" },
    { id: 10, name: "MongoDB" },
    { id: 11, name: "SQL" },
    { id: 12, name: "Data Analysis" },
    { id: 13, name: "Machine Learning" },
    { id: 14, name: "Deep Learning" },
    { id: 15, name: "Computer Vision" },
    { id: 16, name: "UI/UX Design" },
    { id: 17, name: "Project Management" },
    { id: 18, name: "Agile Methodologies" },
    { id: 19, name: "Scrum" },
    { id: 20, name: "Time Management" },
    { id: 21, name: "Communication" },
    { id: 22, name: "Problem Solving" },
    { id: 23, name: "Critical Thinking" },
    { id: 24, name: "Leadership" },
    { id: 25, name: "SEO" },
    { id: 26, name: "Digital Marketing" },
    { id: 27, name: "Content Writing" },
    { id: 28, name: "Public Speaking" },
    { id: 29, name: "Negotiation" },
    { id: 30, name: "Teamwork" },
    { id: 31, name: "Networking" },
    { id: 32, name: "Cloud Computing" },
    { id: 33, name: "Cybersecurity" },
    { id: 34, name: "Blockchain" },
    { id: 35, name: "DevOps" },
    { id: 36, name: "Docker" },
    { id: 37, name: "Kubernetes" },
    { id: 38, name: "Artificial Intelligence" },
    { id: 39, name: "Data Mining" },
    { id: 40, name: "Ethical Hacking" },
    // Add more as necessary
  ];
  
  export default skillsData;
  